{"level":"error","message":"Erro na conexão ao banco de  dados! connect ECONNREFUSED 127.0.0.1:3306","name":"SequelizeConnectionRefusedError","original":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-4078,"fatal":true,"port":3306,"syscall":"connect"},"parent":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-4078,"fatal":true,"port":3306,"syscall":"connect"},"stack":"SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306\n    at ConnectionManager.connect (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:92:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async ConnectionManager._connect (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:220:24)\n    at async C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\sequelize.js:304:26\n    at async Sequelize.authenticate (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\sequelize.js:456:5)\n    at async Sequelize.hasConection (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\src\\database\\index.js:23:5)","timestamp":"2022-11-17T00:03:56.543Z"}
{"level":"error","message":"Erro na conexão ao banco de  dados! Access denied for user ''@'localhost' (using password: NO)","name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user ''@'localhost' (using password: NO)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user ''@'localhost' (using password: NO)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user ''@'localhost' (using password: NO)\n    at ConnectionManager.connect (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:94:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async ConnectionManager._connect (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:220:24)\n    at async C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\sequelize.js:304:26\n    at async Sequelize.authenticate (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\sequelize.js:456:5)\n    at async Sequelize.hasConection (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\src\\database\\index.js:21:5)","timestamp":"2022-11-18T22:02:19.403Z"}
{"level":"error","message":"Erro na conexão ao banco de dados! connect ECONNREFUSED 127.0.0.1:3306","name":"SequelizeConnectionRefusedError","original":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-4078,"fatal":true,"port":3306,"syscall":"connect"},"parent":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-4078,"fatal":true,"port":3306,"syscall":"connect"},"stack":"SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306\n    at ConnectionManager.connect (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:92:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async ConnectionManager._connect (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:220:24)\n    at async C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\sequelize.js:304:26\n    at async Sequelize.authenticate (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\sequelize.js:456:5)\n    at async Sequelize.hasConection (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\src\\database\\index.js:21:5)","timestamp":"2022-11-20T21:00:31.065Z"}
{"level":"error","message":"Erro na conexão ao banco de dados! connect ECONNREFUSED 127.0.0.1:3306","name":"SequelizeConnectionRefusedError","original":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-4078,"fatal":true,"port":3306,"syscall":"connect"},"parent":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-4078,"fatal":true,"port":3306,"syscall":"connect"},"stack":"SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306\n    at ConnectionManager.connect (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:92:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async ConnectionManager._connect (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:220:24)\n    at async C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\sequelize.js:304:26\n    at async Sequelize.authenticate (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\sequelize.js:456:5)\n    at async Sequelize.hasConection (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\src\\database\\index.js:21:5)","timestamp":"2022-11-20T21:02:14.483Z"}
{"level":"error","message":"Erro na conexão ao banco de dados! Access denied for user ''@'localhost' (using password: NO)","name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user ''@'localhost' (using password: NO)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user ''@'localhost' (using password: NO)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user ''@'localhost' (using password: NO)\n    at ConnectionManager.connect (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:94:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async ConnectionManager._connect (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:220:24)\n    at async C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\sequelize.js:304:26\n    at async Sequelize.authenticate (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\sequelize.js:456:5)\n    at async Sequelize.hasConection (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\src\\database\\index.js:21:5)","timestamp":"2022-11-20T21:04:01.141Z"}
{"level":"error","message":"Erro na conexão ao banco de dados! connect ECONNREFUSED 127.0.0.1:3306","name":"SequelizeConnectionRefusedError","original":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-4078,"fatal":true,"port":3306,"syscall":"connect"},"parent":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-4078,"fatal":true,"port":3306,"syscall":"connect"},"stack":"SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306\n    at ConnectionManager.connect (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:92:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async ConnectionManager._connect (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:220:24)\n    at async C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\sequelize.js:304:26\n    at async Sequelize.authenticate (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\sequelize.js:456:5)\n    at async Sequelize.hasConection (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\src\\database\\index.js:22:5)","timestamp":"2022-11-20T21:14:17.144Z"}
{"level":"error","message":"Erro na conexão ao banco de dados! connect ECONNREFUSED 127.0.0.1:3306","name":"SequelizeConnectionRefusedError","original":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-4078,"fatal":true,"port":3306,"syscall":"connect"},"parent":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-4078,"fatal":true,"port":3306,"syscall":"connect"},"stack":"SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306\n    at ConnectionManager.connect (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\dialects\\mysql\\connection-manager.js:92:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async ConnectionManager._connect (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:220:24)\n    at async C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:174:32\n    at async ConnectionManager.getConnection (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\dialects\\abstract\\connection-manager.js:197:7)\n    at async C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\sequelize.js:304:26\n    at async Sequelize.authenticate (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\node_modules\\sequelize\\lib\\sequelize.js:456:5)\n    at async Sequelize.hasConection (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\src\\database\\index.js:22:5)","timestamp":"2022-11-20T21:15:36.076Z"}
{"level":"error","message":"Erro na conexão ao banco de dados! M is not defined","stack":"ReferenceError: M is not defined\n    at Sequelize.hasConection (C:\\Users\\55219\\Desktop\\clone\\clinica-laVie\\src\\database\\index.js:23:17)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-11-20T21:17:32.258Z"}
